version: "3.1"

services:
  db:
    build:
      context: ./db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  front:
    build:
      context: ./front
    restart: unless-stopped
    ports:
      - 3000:3000
  hasura:
    image: hasura/graphql-engine:v1.3.0.cli-migrations-v2
    restart: unless-stopped
    volumes:
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CORS_DOMAIN: "http://localhost:3000"
    ports:
      - 5000:8080
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
